version: '3.9'

services:
  postgres:
    image: postgres
    container_name: greenhouse-db
    environment:
      POSTGRES_DB: greenhouse_db
      POSTGRES_USER: greenhouseAPI
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: